config {
    type: "table",

    dependencies: [
    "assert_ext_Roles_not_empty",
  ]
}

pre_operations {
  CALL `aman-jarir-uat.aman_test.update_watermark_with_retry`(
      ['Roles'],
      FALSE
    )
}

post_operations {
  CALL `aman-jarir-uat.aman_test.update_watermark_with_retry`(
      ['Roles'],
      TRUE
    )
}

select 
  id as role_id,
  Name as role_name,
  CreatedBy as created_by,
  LastModifiedBy as modified_by,
  CreatedDate as created_date,
  LastModifiedDate as modified_date,
  CURRENT_DATETIME() AS etl_timestamp
from ${ref('ext_Roles')}